export const FOLDER_COLOR_PRESETS = [
  { id: 'blue', label: 'Classic Blue', color: '#507dbc' },
  { id: 'emerald', label: 'Emerald', color: '#10b981' },
  { id: 'indigo', label: 'Indigo', color: '#6366f1' },
  { id: 'rose', label: 'Rose', color: '#f43f5e' },
  { id: 'red', label: 'Red', color: '#B14242' },
  { id: 'amber', label: 'Amber', color: '#f59e0b' },
  { id: 'slate', label: 'Slate', color: '#64748b' },
  { id: 'violet', label: 'Electric Violet', color: '#8b5cf6' },
  { id: 'purple', label: 'Deep Purple', color: '#a855f7' },
  { id: 'fuchsia', label: 'Fuchsia', color: '#d946ef' },
  { id: 'teal', label: 'Teal', color: '#14b8a6' },
  { id: 'cyan', label: 'Cyan', color: '#06b6d4' },
  { id: 'sky', label: 'Sky', color: '#0ea5e9' },
  { id: 'lime', label: 'Lime', color: '#84cc16' },
  { id: 'orange', label: 'Sunset Orange', color: '#f97316' },
  { id: 'zinc', label: 'Neutral Zinc', color: '#71717a' },
] as const
