/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as PlaylistsPlaylistNameRouteImport } from './routes/playlists/$playlistName'
import { Route as SearchYoutubeIndexRouteImport } from './routes/search-youtube/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistNameRoute = PlaylistsPlaylistNameRouteImport.update({
  id: '/playlists/$playlistName',
  path: '/playlists/$playlistName',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchYoutubeIndexRoute = SearchYoutubeIndexRouteImport.update({
  id: '/search-youtube/',
  path: '/search-youtube/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playlists/$playlistName': typeof PlaylistsPlaylistNameRoute
  '/library/': typeof LibraryIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/search-youtube/': typeof SearchYoutubeIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playlists/$playlistName': typeof PlaylistsPlaylistNameRoute
  '/library': typeof LibraryIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/search-youtube': typeof SearchYoutubeIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playlists/$playlistName': typeof PlaylistsPlaylistNameRoute
  '/library/': typeof LibraryIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/search-youtube/': typeof SearchYoutubeIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playlists/$playlistName'
    | '/library/'
    | '/playlists/'
    | '/search-youtube/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playlists/$playlistName'
    | '/library'
    | '/playlists'
    | '/search-youtube'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/playlists/$playlistName'
    | '/library/'
    | '/playlists/'
    | '/search-youtube/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaylistsPlaylistNameRoute: typeof PlaylistsPlaylistNameRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  SearchYoutubeIndexRoute: typeof SearchYoutubeIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistName': {
      id: '/playlists/$playlistName'
      path: '/playlists/$playlistName'
      fullPath: '/playlists/$playlistName'
      preLoaderRoute: typeof PlaylistsPlaylistNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-youtube/': {
      id: '/search-youtube/'
      path: '/search-youtube'
      fullPath: '/search-youtube/'
      preLoaderRoute: typeof SearchYoutubeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaylistsPlaylistNameRoute: PlaylistsPlaylistNameRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  SearchYoutubeIndexRoute: SearchYoutubeIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
