/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsRouteRouteImport } from './routes/playlists/route'
import { Route as DownloadsIndexRouteImport } from './routes/downloads/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as PlaylistsPlaylistNameRouteImport } from './routes/playlists/$playlistName'
import { Route as SearchYoutubeIndexRouteImport } from './routes/search-youtube/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRouteRoute = PlaylistsRouteRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsIndexRoute = DownloadsIndexRouteImport.update({
  id: '/downloads/',
  path: '/downloads/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaylistsRouteRoute,
} as any)
const PlaylistsPlaylistNameRoute = PlaylistsPlaylistNameRouteImport.update({
  id: '/$playlistName',
  path: '/$playlistName',
  getParentRoute: () => PlaylistsRouteRoute,
} as any)
const SearchYoutubeIndexRoute = SearchYoutubeIndexRouteImport.update({
  id: '/search-youtube/',
  path: '/search-youtube/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playlists': typeof PlaylistsRouteRouteWithChildren
  '/playlists/$playlistName': typeof PlaylistsPlaylistNameRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/search-youtube/': typeof SearchYoutubeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playlists/$playlistName': typeof PlaylistsPlaylistNameRoute
  '/downloads': typeof DownloadsIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/search-youtube': typeof SearchYoutubeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playlists': typeof PlaylistsRouteRouteWithChildren
  '/playlists/$playlistName': typeof PlaylistsPlaylistNameRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/search-youtube/': typeof SearchYoutubeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playlists'
    | '/playlists/$playlistName'
    | '/downloads/'
    | '/playlists/'
    | '/search-youtube/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playlists/$playlistName'
    | '/downloads'
    | '/playlists'
    | '/search-youtube'
  id:
    | '__root__'
    | '/'
    | '/playlists'
    | '/playlists/$playlistName'
    | '/downloads/'
    | '/playlists/'
    | '/search-youtube/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaylistsRouteRoute: typeof PlaylistsRouteRouteWithChildren
  DownloadsIndexRoute: typeof DownloadsIndexRoute
  SearchYoutubeIndexRoute: typeof SearchYoutubeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/': {
      id: '/downloads/'
      path: '/downloads'
      fullPath: '/downloads/'
      preLoaderRoute: typeof DownloadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof PlaylistsRouteRoute
    }
    '/playlists/$playlistName': {
      id: '/playlists/$playlistName'
      path: '/$playlistName'
      fullPath: '/playlists/$playlistName'
      preLoaderRoute: typeof PlaylistsPlaylistNameRouteImport
      parentRoute: typeof PlaylistsRouteRoute
    }
    '/search-youtube/': {
      id: '/search-youtube/'
      path: '/search-youtube'
      fullPath: '/search-youtube/'
      preLoaderRoute: typeof SearchYoutubeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlaylistsRouteRouteChildren {
  PlaylistsPlaylistNameRoute: typeof PlaylistsPlaylistNameRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
}

const PlaylistsRouteRouteChildren: PlaylistsRouteRouteChildren = {
  PlaylistsPlaylistNameRoute: PlaylistsPlaylistNameRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
}

const PlaylistsRouteRouteWithChildren = PlaylistsRouteRoute._addFileChildren(
  PlaylistsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaylistsRouteRoute: PlaylistsRouteRouteWithChildren,
  DownloadsIndexRoute: DownloadsIndexRoute,
  SearchYoutubeIndexRoute: SearchYoutubeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
